config:
subcomponents:
  elasticsearch-fluentd-kibana:
    config:
    subcomponents:
      elasticsearch:
        config:
          master:
            persistence:
              storageClass: "gp2"
              size: 4Gi
          data:
            persistence:
              storageClass: "gp2"
              size: 64Gi
  prometheus-grafana:
    config:
    subcomponents:
      grafana:
        config:
          persistence:
            storageClassName: "gp2"
      prometheus:
        config:
          alertmanager:
            persistentVolume:
              storageClass: "gp2"
              size: 4Gi
          server:
            persistentVolume:
              storageClass: "gp2"
              size: 64Gi